apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-redis-deployment
  labels:
    app: go-redis-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-redis-app
  template:
    metadata:
      labels:
        app: go-redis-app
    spec:
      containers:
        - name: go-redis-app
          image: azusachino/go-redis:1.0.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: redis-master
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: go-redis-app-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 9090
      targetPort: 8080
  selector:
    app: go-redis-app