apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
        - name: master
          image: redis:6.2-alpine
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
### Service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    role: master
spec:
  selector:
    app: redis
    role: master
  # default type is ClusterIP
  ports:
    - port: 6379
      targetPort: 6379